//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbakTools.Core.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbakTools.Core.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;Statusy&lt;/key&gt;
        ///  &lt;sort property=&quot;Kolejnosc&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kategoria&quot; width=&quot;146&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Kategoria&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; width=&quot;304&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; /&gt;
        ///    &lt;add headertext=&quot;Kolejność&quot; width=&quot;100&quot; textalign=&quot;2&quot; format=&quot;&quot; propertypath=&quot;Kolejnosc&quot; /&gt;
        ///  &lt;/columns&gt;
        ///&lt;/grid&gt;.
        /// </summary>
        internal static string StatusyDokumentow_grid {
            get {
                return ResourceManager.GetString("StatusyDokumentow_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;StatusyDokumentowSelectView&lt;/key&gt;
        ///  &lt;sort property=&quot;Kolejnosc&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kategoria&quot; width=&quot;146&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Kategoria&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; width=&quot;304&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; /&gt;
        ///  &lt;/columns&gt;
        ///&lt;/grid&gt;.
        /// </summary>
        internal static string StatusyDokumentowSelectView_grid {
            get {
                return ResourceManager.GetString("StatusyDokumentowSelectView_grid", resourceCulture);
            }
        }
    }
}
