//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbakTools.Business.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbakTools.Business.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;OperatorzyView&lt;/key&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;B&quot; width=&quot;39&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;Blokada&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; width=&quot;140&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; /&gt;
        ///    &lt;add headertext=&quot;Imie&quot; width=&quot;140&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Imie&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwisko&quot; width=&quot;140&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Nazwisko&quot; /&gt;
        ///    &lt;add headertext=&quot;Email&quot; width=&quot;150&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Email&quot; /&gt;
        ///    &lt;add headert [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string OperatorzyView_grid {
            get {
                return ResourceManager.GetString("OperatorzyView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;Slownik&lt;/key&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kategoria&quot; width=&quot;211&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Kategoria&quot; /&gt;
        ///    &lt;add headertext=&quot;Wartosc&quot; width=&quot;495&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Wartosc&quot; /&gt;
        ///  &lt;/columns&gt;
        ///&lt;/grid&gt;.
        /// </summary>
        internal static string SlownikView_grid {
            get {
                return ResourceManager.GetString("SlownikView_grid", resourceCulture);
            }
        }
    }
}
