//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbakTools.Handel.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbakTools.Handel.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrakZdjecia {
            get {
                object obj = ResourceManager.GetObject("BrakZdjecia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;DostawyView&lt;/key&gt;
        ///  &lt;sort property=&quot;ID&quot; direction=&quot;Descending&quot; /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;ID&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;ID&quot; /&gt;
        ///    &lt;add headertext=&quot;Data&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Data&quot; /&gt;
        ///    &lt;add headertext=&quot;Dostawca&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Dostawca&quot; /&gt;
        ///    &lt;add headertext=&quot;Rodzaj towaru&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;RodzajTowaru&quot; /&gt;
        ///    &lt;add headertext=&quot;Przewoznik&quot; width=&quot;100&quot; te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DostawyView_grid {
            get {
                return ResourceManager.GetString("DostawyView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;Magazyn.StanyMagazynoweView&lt;/key&gt;
        ///  &lt;properties /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;177&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;TowarKod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertextalign=&quot;0&quot; width=&quot;334&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;TowarNazwa&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Stan mag.&quot; headertextalign=&quot;3&quot; width=&quot;100&quot; textalign=&quot;2&quot; format=&quot;&quot; propertypath=&quot;StanMag&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Rezerwacje&quot; headertexta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Magazyn_StanyMagazynoweView_grid {
            get {
                return ResourceManager.GetString("Magazyn_StanyMagazynoweView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;MagazynAVView&lt;/key&gt;
        ///  &lt;sort property=&quot;TowarKod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;ColumnHeadersHeight&quot; value=&quot;39&quot; type=&quot;System.Int32&quot; /&gt;
        ///    &lt;add name=&quot;GridViewReadOnly&quot; value=&quot;False&quot; type=&quot;System.Boolean&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;170&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;TowarKod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertextalign=&quot;0&quot; width=&quot;405&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;TowarNaz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MagazynAVView_grid {
            get {
                return ResourceManager.GetString("MagazynAVView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;ReklamacjeView&lt;/key&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;ID&quot; width=&quot;50&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;ID&quot; /&gt;
        ///    &lt;add headertext=&quot;Data dodania&quot; width=&quot;104&quot; textalign=&quot;3&quot; format=&quot;yyyy-MM-dd&quot; propertypath=&quot;DataDodania&quot; /&gt;
        ///    &lt;add headertext=&quot;Data modyfikacji&quot; width=&quot;110&quot; textalign=&quot;3&quot; format=&quot;yyyy-MM-dd&quot; propertypath=&quot;DataModyfikacji&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; width=&quot;449&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Kontrahent.Nazwa&quot; /&gt;
        ///    &lt;add headertext=&quot;Status&quot; width=&quot;318&quot; textali [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reklamacje_grid {
            get {
                return ResourceManager.GetString("Reklamacje_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;StanyMagazynoweView&lt;/key&gt;
        ///  &lt;sort property=&quot;Kod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kod&quot; width=&quot;179&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Kod&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; width=&quot;433&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; /&gt;
        ///    &lt;add headertext=&quot;Cena netto&quot; width=&quot;100&quot; textalign=&quot;2&quot; format=&quot;C2&quot; propertypath=&quot;CenaNetto&quot; /&gt;
        ///    &lt;add headertext=&quot;Stan mag.&quot; width=&quot;100&quot; textalign=&quot;2&quot; format=&quot;N2&quot; propertypath=&quot;StanMagazynowy&quot; /&gt;
        ///    &lt;add headertext=&quot;Rezerwacj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StanyMagazynoweView_grid {
            get {
                return ResourceManager.GetString("StanyMagazynoweView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;TowarEnovaView&lt;/key&gt;
        ///  &lt;sort property=&quot;Kod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kod&quot; width=&quot;191&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Kod&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; width=&quot;500&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; /&gt;
        ///    &lt;add headertext=&quot;Cena netto&quot; width=&quot;87&quot; textalign=&quot;2&quot; format=&quot;C2&quot; propertypath=&quot;CenaNetto&quot; /&gt;
        ///    &lt;add headertext=&quot;VAT&quot; width=&quot;51&quot; textalign=&quot;2&quot; format=&quot;&quot; propertypath=&quot;StawkaVat&quot; /&gt;
        ///  &lt;/columns&gt;
        ///&lt;/grid&gt;.
        /// </summary>
        internal static string TowarEnovaView_grid {
            get {
                return ResourceManager.GetString("TowarEnovaView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;TowarEnovaView&lt;/key&gt;
        ///  &lt;sort property=&quot;Kod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kod&quot; width=&quot;191&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Kod&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; width=&quot;500&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; /&gt;
        ///    &lt;add headertext=&quot;Cena netto&quot; width=&quot;87&quot; textalign=&quot;2&quot; format=&quot;C2&quot; propertypath=&quot;CenaNetto&quot; /&gt;
        ///    &lt;add headertext=&quot;VAT&quot; width=&quot;51&quot; textalign=&quot;2&quot; format=&quot;&quot; propertypath=&quot;StawkaVat&quot; /&gt;
        ///  &lt;/columns&gt;
        ///&lt;/grid&gt;.
        /// </summary>
        internal static string TowarEnovaViewSelect_grid {
            get {
                return ResourceManager.GetString("TowarEnovaViewSelect_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;TowaryAtrybutyListaView&lt;/key&gt;
        ///  &lt;sort property=&quot;TowarKod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;LeftPanelSpliterDistance&quot; value=&quot;192&quot; type=&quot;System.Int32&quot; /&gt;
        ///    &lt;add name=&quot;TopPanelSpliterDistance&quot; value=&quot;51&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;263&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;TowarKod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertextalign=&quot;0&quot; width=&quot;334&quot; textalign=&quot;0&quot; format=&quot;&quot; prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TowaryAtrybutyListaView_grid {
            get {
                return ResourceManager.GetString("TowaryAtrybutyListaView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;ZamowieniaView&lt;/key&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;B&quot; width=&quot;27&quot; textalign=&quot;3&quot; propertypath=&quot;Blokada&quot; /&gt;
        ///    &lt;add headertext=&quot;Numer&quot; width=&quot;66&quot; textalign=&quot;1&quot; propertypath=&quot;NumerPelny&quot; /&gt;
        ///    &lt;add headertext=&quot;Data&quot; width=&quot;100&quot; textalign=&quot;1&quot; propertypath=&quot;DataDodania&quot; /&gt;
        ///    &lt;add headertext=&quot;Data aktual.&quot; width=&quot;95&quot; textalign=&quot;1&quot; propertypath=&quot;DataAtualizacji&quot; /&gt;
        ///    &lt;add headertext=&quot;PR&quot; width=&quot;26&quot; textalign=&quot;1&quot; propertypath=&quot;PrzedstawicielKod&quot; /&gt;
        ///    &lt;add headertext=&quot;Kontrahent&quot; widt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZamowieniaView_grid {
            get {
                return ResourceManager.GetString("ZamowieniaView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;ZamowienieMagazynAVView&lt;/key&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;TopPanelSpliterDistance&quot; value=&quot;49&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;243&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;TowarKod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;TowarNazwa&quot; headertextalign=&quot;0&quot; width=&quot;357&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;TowarNazwa&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Atrybut&quot; headertextalign=&quot;0&quot; width=&quot;240&quot; textalign=&quot;1&quot; format=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZamowienieMagazynAVView_grid {
            get {
                return ResourceManager.GetString("ZamowienieMagazynAVView_grid", resourceCulture);
            }
        }
    }
}
