//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbakTools.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbakTools.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;KontaktyView&lt;/key&gt;
        ///  &lt;sort property=&quot;EMAIL&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;EMAIL&quot; headertextalign=&quot;0&quot; width=&quot;285&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;EMAIL&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertextalign=&quot;0&quot; width=&quot;249&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Telefon komorkowy&quot; headertextalign=&quot;0&quot; width=&quot;245&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;TelefonKomorkowy&quot; readonly=&quot;True&quot; / [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string KontaktyView_grid {
            get {
                return ResourceManager.GetString("KontaktyView_grid", resourceCulture);
            }
        }
    }
}
