//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbakTools.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbakTools.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;KontaktyView&lt;/key&gt;
        ///  &lt;sort property=&quot;EMAIL&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;EMAIL&quot; headertextalign=&quot;0&quot; width=&quot;285&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;EMAIL&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertextalign=&quot;0&quot; width=&quot;249&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Nazwa&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Telefon komorkowy&quot; headertextalign=&quot;0&quot; width=&quot;245&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;TelefonKomorkowy&quot; readonly=&quot;True&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KontaktyView_grid {
            get {
                return ResourceManager.GetString("KontaktyView_grid", resourceCulture);
            }
        }
    }
}
