//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enova.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enova.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;DokumentyEnovaView&lt;/key&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Z&quot; width=&quot;23&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;Zatwierdzony&quot; /&gt;
        ///    &lt;add headertext=&quot;A&quot; width=&quot;21&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;Anulowany&quot; /&gt;
        ///    &lt;add headertext=&quot;K&quot; width=&quot;23&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;Korekta&quot; /&gt;
        ///    &lt;add headertext=&quot;Data&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Data&quot; /&gt;
        ///    &lt;add headertext=&quot;Numer&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;NumerPelny&quot; /&gt;
        ///    &lt;add hea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DokumentyEnovaView_grid {
            get {
                return ResourceManager.GetString("DokumentyEnovaView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;KompensatyView&lt;/key&gt;
        ///  &lt;sort property=&quot;NumerPelny&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;columnheadersheight&quot; value=&quot;27&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Data&quot; headertextalign=&quot;3&quot; width=&quot;126&quot; textalign=&quot;3&quot; format=&quot;d&quot; propertypath=&quot;Data&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Numer&quot; headertextalign=&quot;0&quot; width=&quot;107&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;NumerPelny&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KompensatyView_grid {
            get {
                return ResourceManager.GetString("KompensatyView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;KontrahenciEnovaView&lt;/key&gt;
        ///  &lt;sort property=&quot;Kod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;LeftPanelSpliterDistance&quot; value=&quot;175&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;BS&quot; headertextalign=&quot;3&quot; width=&quot;42&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;BlokadaSprzedaży&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;228&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Kod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertextalign= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KontrahenciEnovaView_grid {
            get {
                return ResourceManager.GetString("KontrahenciEnovaView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;KontrahenciEnovaViewSelect&lt;/key&gt;
        ///  &lt;sort property=&quot;Kod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;LeftPanelSpliterDistance&quot; value=&quot;187&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;BS&quot; headertextalign=&quot;0&quot; width=&quot;34&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;BlokadaSprzedaży&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;204&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Kod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertext [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KontrahenciEnovaViewSelect_grid {
            get {
                return ResourceManager.GetString("KontrahenciEnovaViewSelect_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grid&gt;
        ///  &lt;key&gt;PozycjeKompensatyView&lt;/key&gt;
        ///  &lt;sort property=&quot;DataDokumentu&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Data&quot; headertextalign=&quot;3&quot; width=&quot;75&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;DataDokumentu&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Numer dokumentu&quot; headertextalign=&quot;0&quot; width=&quot;174&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;NumerDokumentu&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Należność&quot; headertextalign=&quot;0&quot; width=&quot;115&quot; textalign=&quot;2&quot; format=&quot;&quot; propertypath=&quot;N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PozycjeKompensatyView_grid {
            get {
                return ResourceManager.GetString("PozycjeKompensatyView_grid", resourceCulture);
            }
        }
    }
}
