//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enova.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enova.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;DokumentyEnovaView&lt;/key&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Z&quot; width=&quot;23&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;Zatwierdzony&quot; /&gt;
        ///    &lt;add headertext=&quot;A&quot; width=&quot;21&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;Anulowany&quot; /&gt;
        ///    &lt;add headertext=&quot;K&quot; width=&quot;23&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;Korekta&quot; /&gt;
        ///    &lt;add headertext=&quot;Data&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;Data&quot; /&gt;
        ///    &lt;add headertext=&quot;Numer&quot; width=&quot;100&quot; textalign=&quot;1&quot; format=&quot;&quot; propertypath=&quot;NumerPelny&quot; /&gt;
        ///    &lt;add hea [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string DokumentyEnovaView_grid {
            get {
                return ResourceManager.GetString("DokumentyEnovaView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;KompensatyView&lt;/key&gt;
        ///  &lt;sort property=&quot;NumerPelny&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;columnheadersheight&quot; value=&quot;27&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Data&quot; headertextalign=&quot;3&quot; width=&quot;126&quot; textalign=&quot;3&quot; format=&quot;d&quot; propertypath=&quot;Data&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Numer&quot; headertextalign=&quot;0&quot; width=&quot;107&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Numer.NumerPelny&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign= [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string KompensatyView_grid {
            get {
                return ResourceManager.GetString("KompensatyView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;KontrahenciEnovaView&lt;/key&gt;
        ///  &lt;sort property=&quot;Kod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;LeftPanelSpliterDistance&quot; value=&quot;175&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;BS&quot; headertextalign=&quot;3&quot; width=&quot;42&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;BlokadaSprzedaży&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;228&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Kod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertextalign= [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string KontrahenciEnovaView_grid {
            get {
                return ResourceManager.GetString("KontrahenciEnovaView_grid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;KontrahenciEnovaViewSelect&lt;/key&gt;
        ///  &lt;sort property=&quot;Kod&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties&gt;
        ///    &lt;add name=&quot;LeftPanelSpliterDistance&quot; value=&quot;187&quot; type=&quot;System.Int32&quot; /&gt;
        ///  &lt;/properties&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;BS&quot; headertextalign=&quot;0&quot; width=&quot;34&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;BlokadaSprzedaży&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Kod&quot; headertextalign=&quot;0&quot; width=&quot;204&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;Kod&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Nazwa&quot; headertext [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string KontrahenciEnovaViewSelect_grid {
            get {
                return ResourceManager.GetString("KontrahenciEnovaViewSelect_grid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;grid&gt;
        ///  &lt;key&gt;PozycjeKompensatyView&lt;/key&gt;
        ///  &lt;sort property=&quot;DataDokumentu&quot; direction=&quot;Ascending&quot; /&gt;
        ///  &lt;properties /&gt;
        ///  &lt;columns&gt;
        ///    &lt;add headertext=&quot;Data&quot; headertextalign=&quot;3&quot; width=&quot;75&quot; textalign=&quot;3&quot; format=&quot;&quot; propertypath=&quot;DataDokumentu&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Numer dokumentu&quot; headertextalign=&quot;0&quot; width=&quot;174&quot; textalign=&quot;0&quot; format=&quot;&quot; propertypath=&quot;NumerDokumentu&quot; readonly=&quot;True&quot; /&gt;
        ///    &lt;add headertext=&quot;Należność&quot; headertextalign=&quot;0&quot; width=&quot;115&quot; textalign=&quot;2&quot; format=&quot;&quot; propertypath=&quot;N [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PozycjeKompensatyView_grid {
            get {
                return ResourceManager.GetString("PozycjeKompensatyView_grid", resourceCulture);
            }
        }
    }
}
